### ISSUE TITLE
Random Insignias for GLT units

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#100]
Playable GLT units should have random insignias:

Classnames:
GLT_Patch_Chairborne
GLT_Patch_Drunk
GLT_Patch_Ducttape
GLT_Patch_Eagle
GLT_Patch_Fuckface
GLT_Patch_Fuckyou
GLT_Patch_Major_League_Infidel
GLT_Patch_Merkel
GLT_Patch_Retard

**Comment by Legislator** [comment]
if (!isDedicated) then { 
     _insignia = ["GLT_Patch_Chairborne", "GLT_Patch_Drunk", "GLT_Patch_Ducttape", "GLT_Patch_Eagle", "GLT_Patch_Fuckface", "GLT_Patch_Fuckyou", "GLT_Patch_Major_League_Infidel", "GLT_Patch_Merkel", "GLT_Patch_Retard"] call BIS_fnc_selectRandom;  
     player setVariable ["glt_random_player_insignia", _insignia, true]; 
}; 

{ 
     waitUntil {!(isNil {_x getVariable "glt_random_player_insignia"})}; 
     _insignia = _x getVariable "glt_random_player_insignia"; 
     [_x, _insignia] call BIS_fnc_setUnitInsignia; 
} foreach (playableUnits + switchableUnits);

**Comment by Legislator** [comment]
Code has been tested in the init.sqf. Though the code itself is working, the following code of the init.sqf is ignored.

**Comment by sxp2high** [comment]
This should work in MP & SP, AI & Player:

```
[] spawn {

    sleep 0.1;

    {

        if (local _x) then  {

            _insignia = ["GLT_Patch_Chairborne", "GLT_Patch_Drunk", "GLT_Patch_Ducttape", "GLT_Patch_Eagle", "GLT_Patch_Fuckface", "GLT_Patch_Fuckyou", "GLT_Patch_Major_League_Infidel", "GLT_Patch_Merkel", "GLT_Patch_Retard"] call BIS_fnc_selectRandom;

            _x setVariable ["glt_random_player_insignia", _insignia, true];

        } else {

            waitUntil {!(isNil {_x getVariable "glt_random_player_insignia"})};

        };

        _insignia = _x getVariable "glt_random_player_insignia";
        [_x, _insignia] call BIS_fnc_setUnitInsignia;

    } forEach (playableUnits + switchableUnits);

};
```

Spawn and sleep 0.1 to make sure locality is final. (Players are local on server very early in mission init)

**Comment by Legislator** [comment]
Code is working and has been applied to GLT missions having playable GLT units.
