### ISSUE TITLE
GLT Vest Flecktarn - RPT Issue

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#109]
Warning Message: Cannot load material file glt_items_vests_glt_flecktarn\data\vests.rvmat.

**Comment by sxp2high** [comment]
This one too, from the Server RPT:

```
Warning Message: Cannot load material file glt_items_uniforms_glt_flecktarn\data\clothing1.rvmat.
```

**Comment by Legislator** [comment]
The issue was caused during the file binarization. It erased the RVMAT file ... tropentarn and NDK vests are also effected.

**Comment by Legislator** [comment]
PBO will remain unbinarized ... situation not critical
