### ISSUE TITLE
Player starts at random position - respawn manager related issue

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#112]
The player is starting at a random position according to the defined array: 

<code>
{ [west, _x] call BIS_fnc_addRespawnPosition; } forEach ["Refugee Camp", Mobile_Respawn];  
</code>

It's also breaking the real random starting position which is used in some missions via
<code>  nul = [[start1, start2, start3]] spawn GLT_fnc_RandomPos;
</code>

**Comment by sxp2high** [comment]
Ticket: http://feedback.arma3.com/view.php?id=18823

Will try to fix it later.

**Comment by sxp2high** [comment]
_null = [] execVM "startPos.sqf";

[startPos.sqf](http://arma3.cc/temp/startPos.sqf)

Hope it works, tested a couple times, seemed OK.

**Comment by Legislator** [comment]
Fix has been applied to all missions.

**Comment by Legislator** [comment]
The issue with the random startup position occured again in GLT Mod 1.22, GLT 20 - Winter is coming, short version.

init.sqf: http://pastebin.com/HZR73XMj

Has the fix been correctly applied?

**Comment by sxp2high** [comment]
Remove the startPos.sqf

Different approach, using PBO.

This will now replace BIS_fnc_moveToRespawnPosition, which will exit (do nothing) on first call (Mission start and JIP).

http://arma3.cc/temp/glt_startpos_fix.rar

**Comment by Legislator** [comment]
PBO has been included in the GLT Mod
