### ISSUE TITLE
GLT 07: Operation Icarus + 18: Men in Fleck - Unit does not move

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#129]
After completing task 1 the hostage joins the group, but does not move. It doesn't respond to commands.

**Comment by Legislator** [comment]
So far no script error.

<code>
    // Scientist joins player group
    [] spawn { 
         waitUntil {(east countSide list trg3 < 1)};  
            [Unit1_Scientist] joinSilent (group ((switchableUnits + playableUnits) select 0)); 
            Unit1_Scientist enableAI "MOVE"; 
            Unit1_Scientist enableAI "AUTOTARGET";
    };
</code>

**Comment by Legislator** [comment]
Situation needs to be checked again.

**Comment by Legislator** [comment]
On tuesday the situation happened again. The unit joined the player group and did not move anymore. Using the server console to apply move commands did not work.

**Comment by sxp2high** [comment]
1. Change his init line, to make sure only server executes:
   
   ```
   if (isServer) then { this disableAI "MOVE"; this disableAI "AUTOTARGET"; this setUnitPos "UP"; };
   ```
2. Now, joinSilent will transfer the AI control (locality) from server to group leader (player) and I think there lies the problem. Try to enable his AI before joining the group:
   
   ```
   [] spawn { 
        waitUntil {(east countSide list trg3 < 1)}; 
   
       Unit1_Scientist enableAI "MOVE";
       Unit1_Scientist enableAI "AUTOTARGET";
       sleep 3;
       [Unit1_Scientist] joinSilent (group ((switchableUnits + playableUnits) select 0));
   };
   ```

**Comment by Legislator** [comment]
Fix has been applied. SP test is ok.

**Comment by Legislator** [comment]
MP test not successful! It seems like enableAI "MOVE" is not executed in MP mode anymore.

**Comment by Legislator** [comment]
GLT 07: Operation Icarus is also affected with this issue. The mission had not been changed since june 2014 and was always working.

**Comment by sxp2high** [comment]
OK, sorry, I will do some testing and find a solution.

**Comment by sxp2high** [comment]
Not able to reproduce. (Tried 5 times on dedicated)

Strange problem. Can't fix it, if I can't find the problem.

I can only suggest a different approach.

This will have the same effect as disableAI basically, plus setPosATL (maybe he get's stuck sometimes on spawn?), I measured the building's floor at ~0.7 meters ATL.

Init line:

``` sqf
if (isServer) then { this allowFleeing 0; doStop this; this setBehaviour "CARELESS"; this setUnitPos "UP"; this setPosATL [((getPosATL this) select 0), ((getPosATL this) select 1), 0.75]; };
```

After that, he only has to join:

``` sqf
[] spawn { 
     waitUntil {(east countSide list trg3 < 1)};
    [Unit1_Scientist] joinSilent (group ((switchableUnits + playableUnits) select 0)); 
};
```

**Comment by Legislator** [comment]
Working code has been applied to all 3 missions (confirmed working in GLT 04: Operation Delphi
