### ISSUE TITLE
Critical bug in First Aid script

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#193]
There is a critical bug in the first aid script

Environment: Editor, SP + MP dedicated server
Issue: You can't drop a player anymore that has been carried; player gets stucked in animation

**Comment by sxp2high** [comment]
Thanks, I will remove carrying from the action menu for the next build. The animation is just terrible. I've spend too much time on that already. Not worth it.

**Comment by Legislator** [comment]
Fix has been applied to glt_core
