### ISSUE TITLE
Random inventory items

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#203]
I need some code that can be executed for any mission:
- scan whole map for "man" units
- add one random inventory from an array of pre-defined inventory items
- enable whitelist option of units that are not affected by this feature (f.e. player units and mission-critical units)

**Comment by sxp2high** [comment]
Define **glt_items**.  
`glt_items = ["GLT_Item_Spraycan_Black"];`

**fn_items:**  

``` sqf
private ["_items","_blacklist","_units"];


_items = glt_items;
_blacklist = _this select 0;
_units = (allUnits - _blacklist);


{

    private ["_unit","_item"];

    _unit = _x;

    if (local _unit) then {
        _item = _items call BIS_fnc_selectRandom;
        if (_unit canAdd _item) then { _unit addItem _item; };
    };

} forEach _units;


true
```

**Syntax:**  
`_done = [(switchableUnits + playableUnits)] call fn_items;`
or
`_done = [((switchableUnits + playableUnits) + [_unit1, _unit2])] call fn_items;`

**Comment by Legislator** [comment]
Code has been applied to GLT_fnc_Items and to \glt_core\scripts\startup\main.sqf
