### ISSUE TITLE
GLT 01: Meet the Spartans - RPT Flooding

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#219]
Critical issue, over 3 GB RPT file on the Server.

``` sqf
11:02:46   Error position: <gw1) == {alive _x} count (units gw1))}; >
11:02:46   Error Undefined variable in expression: gw1
11:02:46 File glt_missions_stratis\missions\glt_01_meet_the_spartans.stratis\init.sqf, line 140
```

**Comment by Legislator** [comment]
waitUntil {({(_x in list trg4)} count (units gw1) == {alive _x} count (units gw1))}; 

squadleader unit p1 is defining the group via "gw1 = group this;". p1 was not used in the test. group initialization has been applied to all group members.
