### ISSUE TITLE
GLT Showcase: IFV Namer Destroy Waypoint Issue

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#220]
Engine is complaining about a destroy waypoint, thousands of lines of warnings in the RPT.

``` sqf
21:42:32 Destroy waypoint not linked to a target: Near target acquisition is slow and may even select friendly unit.
```

Destroy waypoint needs to be attached to a unit/vehicle/object.

**Comment by Legislator** [comment]
Waypoint has been changed to "Search & Destroy" ... I'm glad this was the only one as they are not easy to identify.
