### ISSUE TITLE
First Aid - TFR related error

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#222]
There is an RPT error when you don't load task force radio addon:

19:02:07 Error in expression <all cba_fnc_getKeybind;

_actualKey = ((_keybind select 5) select 0);
btk_firdst>
19:02:07   Error position: <_keybind select 5) select 0);
btk_firdst>
19:02:07   Error Undefined variable in expression: _keybind
19:02:07 File glt_core\scripts\revive\btk_firstaid\init.sqf, line 128

**Comment by sxp2high** [comment]
Thanks. Fixed in next build.
