### ISSUE TITLE
Floating hands of Middle East Unit Model

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#226]
![ab42zj6](https://cloud.githubusercontent.com/assets/7606291/7797792/5552bd9c-02f1-11e5-9a18-1f88ba571b56.jpg)

**Comment by ruPaladin** [comment]
Made some good east terrorists with help of GLT mod, RHS and tactical beard mod. Only one thing disappoint me - hands. Any news about that problem fix? Sorry for that question, I know it is hard to mod especially such a big mod.

**Comment by Legislator** [comment]
It's not fixed yet. I'm currently reworking the CDF units and I intend to release a small update for GLT Extended in July (which also requires a small update for GLT Mod). Maybe I can push it into the small update cycle.

**Comment by Legislator** [comment]
Affected:
glt_clothes_middle_east2.p3d
GLT_Clothes_Middle_East6
GLT_Clothes_Middle_East7
GLT_Clothes_Middle_East8
GLT_Clothes_Middle_East9
GLT_Clothes_Middle_East10

glt_clothes_middle_east3.p3d
GLT_Clothes_Middle_East11
GLT_Clothes_Middle_East12
GLT_Clothes_Middle_East13
GLT_Clothes_Middle_East14
GLT_Clothes_Middle_East15

glt_clothes_middle_east4.p3d
GLT_Clothes_Middle_East16
GLT_Clothes_Middle_East17
GLT_Clothes_Middle_East18
GLT_Clothes_Middle_East19
GLT_Clothes_Middle_East20

glt_clothes_middle_east5.p3d
GLT_Clothes_Middle_East21
GLT_Clothes_Middle_East22
GLT_Clothes_Middle_East23
GLT_Clothes_Middle_East24
GLT_Clothes_Middle_East25

glt_clothes_middle_east6.p3d
GLT_Clothes_Middle_East26
GLT_Clothes_Middle_East27
GLT_Clothes_Middle_East28
GLT_Clothes_Middle_East29
GLT_Clothes_Middle_East30

**Comment by Legislator** [comment]
fixed: glt_clothes_middle_east2.p3d

**Comment by Legislator** [comment]
fixed: floating hands
fixed: textures and RVMAT issues
added: thermal images on all models

**Comment by ruPaladin** [comment]
Thank you so much! Hope to see an update soon.
