### ISSUE TITLE
Respawn Loadout Code Update

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#227]
The respawn gear laodout code:

``` sqf
if !(isDedicated) then {
    player addEventHandler ["killed", { [] spawn { waitUntil {(alive player)}; [] call GLT_fnc_loadGear; }; }];

    [] spawn { 
     while {true} do { 
          sleep 5.238; 
          if (alive player) then { call GLT_fnc_saveGear; } else { waitUntil {(alive player)}; }; 
        }; 
    };
};
```

Should be replaced with BTK_fnc_gearRespawn:

``` sqf
_null = [] spawn BTK_fnc_gearRespawn;
```

It will do the same thing, saving every couple of seconds and restore the saved after respawn.

If, for whatever reason, saving is not desired for a certain time, it can be paused with:

``` sqf
btk_gear_respawn_paused = true;
```

And resumed afterwards with:

``` sqf
btk_gear_respawn_paused = nil;
```

**Comment by Legislator** [comment]
All Stratis missions have been applied with it.

**Comment by Legislator** [comment]
Doesn't work ... old gear is invisible on the ground, not loaded automatically into player inventory. Old code has been applied to Stratis missions.

**Comment by Legislator** [comment]
Issue might be related to this code error
21:20:27 Error in expression <} else {

if (btk_playerrestore_vehicle != _vehicle) then {
btk_playerrestore_ve>
21:20:27   Error position: <!= _vehicle) then {
btk_playerrestore_ve>
21:20:27   Error Generic error in expression
21:20:27 File btk_playerrestore\functions\fn_playerSave.sqf, line 139
