### ISSUE TITLE
Low setSkill problematic

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#24]
**Problem:**
I noticed that in GLT: Showcase Paratroopers - 1.00, this code is used:  
`{_x setSkill (random 0.2)} foreach thislist;`  

This is very problematic, because it will not only change the units ability to shoot accurately.
This will make the AI very stupid, blind, unresponsive, afraid and use bad tactics. We saw that in action. I tested it, and ALL subskills had extremely low values, 0.0x most of them. This has almost the same effect as disableAI.

At least **spotdistance, spottime, commanding, courage** should have higher values for interesting gameplay and more realistic behavior.  

**Suggestion:**
Define skill set somewhere (centralized I would say):

``` C++
glt_ai_skill = [
["aimingspeed", 0.3],
["aimingaccuracy", 0.2],
["aimingshake", 0.5],
["spotdistance", 1],
["spottime", 0.5],
["commanding", 1],
["courage", 0.5],
["endurance", 0.5],
["reloadSpeed", 0.5],
["general", 1]
];
```

Then use setSkill array (https://community.bistudio.com/wiki/setSkill_array) instead:

``` C++
nul = thisList spawn {

    {
        _unit = _x;
        {
            _unit setSkill _x;
        } forEach glt_ai_skill;
    } forEach _this;

};
```

The above values are just an example - I have no real experience with them, we will have to test them in real situations! Read more about the skills here https://community.bistudio.com/wiki/AI_Sub-skills  

I'm going to test the sub skills in great detail within Survive, but I'm not there yet.

**Comment by Legislator** [comment]
I always use setSkill 1 on all friendly and hostile aircrafts. Would it still be possible to use this later on?

**Comment by sxp2high** [comment]
Sure, it's the same method using a trigger.

**Comment by Legislator** [comment]
Working in GLT Showcase Paratroopers. Will be applied to every mission over the time.
