### ISSUE TITLE
GLT: Operation Desert Comb - 1.01 Not starting

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#246]
Mission is not starting on server:

> 20:42:28 Missing addons detected:
> 20:42:28   blastcore_vep
> 20:42:28 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.blastcore_vep

**Comment by Legislator** [comment]
addon blastcore_vep has been removed from mission.sqm
