### ISSUE TITLE
GLT Poster Module RPT Error

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#338]
The following error occured in GLT 08: Insurrection

22:55:53 Error in expression <ct call bis_fnc_moduleTriggers);
};
};

_result>
22:55:53   Error position: <_result>
22:55:53   Error Undefined variable in expression: _result
22:55:53 File A3\functions_f\Modules\fn_moduleUnits.sqf [BIS_fnc_moduleUnits], line 40

**Comment by sxp2high** [comment]
Need more info

**Comment by Legislator** [comment]
Issue is not present anymore in build GLT Mod 2.03.2024.05.01
