### ISSUE TITLE
Insignia Applier

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#451]
Create a module that can be placed in the editor. Once placed the player should be able to open a dialogue by pressing a key. All Arma 3 insignias are included in the class CfgUnitInsignia. In mission I applied the insignia in the init.sqf using

{[_x, "GLT_Patch_Sparta"] call BIS_fnc_setUnitInsignia;} foreach (playableUnits + switchableUnits);

It should be possible either to display all available insiginias or to use a whitelist.

**Comment by sxp2high** [comment]
[btk_changeinsignia.zip](https://github.com/Legislator/GLT-Mod/files/15099644/btk_changeinsignia.zip)

Addon attached. It's client-side only.

**BTK Change Insignia**
A dialog interface to change insignia (shoulder patch) on-the-fly. The addon also includes a bug fix for the base game, that makes insignias respawn compatible.

**Keybinds**
By default (Left Windows + I)
To change or view your keybinds open **_Arma 3 options_** > **_Controls_** > **_Scroll down in the category list_**

**Mission maker notes:**
You can enable and disable the option to change insignia during the mission at any point:
```
btk_changeinsignia_disabled = true; // Functionality disabled
btk_changeinsignia_disabled = nil; // Functionality restored
```

You can limit or extend the available insignias during the mission at any point:
```
btk_changeinsignia_whitelist = ["111thID"];
sleep 5;
hint "New insignia available!";
btk_changeinsignia_whitelist = ["111thID","TFAegis"];
```


More info and standalone release will be available soon on its dedicated repository: https://github.com/sxp2high/BTK-Change-Insignia

**Comment by Legislator** [comment]
So far all multiplayer tests were successful. It can be reintegrated into GLT Mod 2.03
