### ISSUE TITLE
GLT Showcase KSK - Trigger issues

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#48]
Task 6 did not appear
**init.sqf**
<code>
if (isServer) then {
    // Task 6
    [] spawn { 
         waitUntil {((count (nearestObjects[getPos Pos1, ["O_Heli_Attack_02_F"], 250]))> 0)}; 
            nul = [] execVM "\glt_core\scripts\tasks\task_create.sqf";

```
        [[(playableUnits + switchableUnits), "task6", localize "STR_task6_goal_sc_ksk", localize "STR_task6_text_sc_ksk", localize "STR_task6_goal_sc_ksk", (getMarkerPos "Military Base"), true, false], "GLT_fnc_createTask", nil, true, true] spawn BIS_fnc_MP;
};
```

};</code>

Task 3 was not solved in the briefing
**init.sqf**
<code>
if (!isDedicated) then {

```
// Task 3
[] spawn { 
     waitUntil {"GLT_Item_Laptop_Unfolded" in (items player)}; 
        nul = ["task3", "Succeeded"] execVM "\glt_core\scripts\tasks\task.sqf";

        obj3 = true;
        publicVariable "obj3";
};
```

};</code>

**RPT Error**
Error in expression <ayer)) then { [("Task" + _status), ["", _taskTitle]] call BIS_fnc_showNotificati>
  Error position: <_taskTitle]] call BIS_fnc_showNotificati>
  Error Undefined variable in expression: _tasktitle
File glt_core\glt_functions\fnc_tasks\fn_setTaskState.sqf, line 51
Error in expression <r = _unit getVariable _taskId;

_task = _taskVar select 0;
_taskTitle = _taskVar>
  Error position: <_taskVar select 0;
_taskTitle = _taskVar>
  Error Undefined variable in expression: _taskvar
File glt_core\glt_functions\fnc_tasks\fn_setTaskState.sqf, line 46

**Comment by sxp2high** [comment]
Careful with nearestObjects, it's a very performance intense command, never use it in waitUntil (checked once every frame) without sleep.
nearEntities is much less performance heavy and should be used instead whenever possible.

```
waitUntil {sleep 2; (((getPosATL Pos1) nearEntities ["O_Heli_Attack_02_F", 250]) > 0)}; // Much better

waitUntil {sleep 2; ((count (nearestObjects[getPos Pos1, ["O_Heli_Attack_02_F"], 250]))> 0)}; // Still better

while {((count (nearestObjects[getPos Pos1, ["O_Heli_Attack_02_F"], 250])) == 0)} do { sleep 2; }; // Pretty much the same
```

250 is not enough, 250 means hes hovering above the FOB pretty much, I'd use:

```
waitUntil {sleep 1; ((Unit1_Mi48 distance pos1) < 600)};
```

**Comment by Legislator** [comment]
Changes have been applied. I still need help with task 3 which was not solved once the player took the item into the inventory.

**Comment by Legislator** [comment]
nul = ["task3", "Succeeded"] execVM "\glt_core\scripts\tasks\task.sqf"; has been replaced with [[["task3", "Succeeded"], "\glt_core\scripts\tasks\task.sqf"], "BIS_fnc_execVM", false, false] spawn BIS_fnc_MP;

**Comment by Legislator** [comment]
During the last session, Task 3 had not been labeled as resolved though the player picked up the laptop item. The end trigger was not activated.

**Comment by Legislator** [comment]
I tested it myself again in A3 1.36 and there was no issue at all. Strange behaviour.
