### ISSUE TITLE
GLT 12: Kill Farm - Mission stops after arrived at Kill Farm

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#5]
The mission does not continue after the player arrived at the Kill Farm thus completing Task 1.

**Comment by sxp2high** [comment]
It's a locality issue. (group player) doesn't work on the server, because there is no "player" on the server.

Change the trigger from
nul = [] execVM "tasks\task1_done.sqf";

to:
nul = ["tasks\task1_done.sqf","BIS_fnc_execVM", true, false] spawn BIS_fnc_MP;

to make it activate on the server.
