### ISSUE TITLE
GLT 18: Men in Fleck - Hostage joins empty group

### ISSUE THREAD

**Issue by Legislator** [Legislator/GLT-Mod#8]
If no player is using unit p1, the hostage will join an empty group remaining out of control.

Code right now:
[Unit1_Scientist] joinSilent p1;

**Comment by sxp2high** [comment]
Find player group:
[Unit1_Scientist] joinSilent (group ((switchableUnits + playableUnits) select 0));

**Comment by Legislator** [comment]
Will apply code to GLT 04: Operation Delphi as well.
