### ISSUE TITLE
GLT 01: Meet the Spartans - Error Undefined variable in expression: usa_grp1

### ISSUE THREAD

**Issue by sxp2high** [Legislator/GLT-Mod#91]
```
Error in expression <f", "ColorBlue", "Sparta 3", 1, (leader usa_grp1), 1] spawn GLT_fnc_Marker;>
  Error position: <usa_grp1), 1] spawn GLT_fnc_Marker;>
  Error Undefined variable in expression: usa_grp1
File glt_missions_stratis\missions\glt_01_meet_the_spartans.stratis\us_spawn.sqf, line 8
```

Results in:

```
Error in expression <tMarkerText _markerText;


while {alive _unit} do {
_marker setMarkerPos (getPos>
  Error position: <_unit} do {
_marker setMarkerPos (getPos>
  Error Undefined variable in expression: _unit
File glt_core\glt_functions\fnc_marker\fnc_marker.sqf, line 25
```

And:

```
Error in expression <
_delay = _this select 6;


if (!(local _unit)) exitWith {};

if (isPlayer _unit>
  Error position: <_unit)) exitWith {};

if (isPlayer _unit>
  Error Undefined variable in expression: _unit
File glt_core\glt_functions\fnc_marker\fnc_marker.sqf, line 12
```

**Comment by Legislator** [comment]
Issue could not be reproduced. It might be possible that the group was not spawned when the marker had been created. Or the groupleader was dead right after spawning.

<code>if (isServer) then {
    usa_grp1 = [getMarkerPos "Houses", west, (configFile >> "CfgGroups" >> "WEST" >> "BLU_F" >> "Infantry" >> "BUS_InfSquad")] call BIS_fnc_spawnGroup; 
    [usa_grp1, getMarkerPos "Camp Maxwell", 100] call BIS_fnc_taskAttack;
};

sleep 1;

nul = ["Marker4_NATO", "b_inf", "ColorBlue", "Sparta 3", 1, (leader usa_grp1), 1] spawn GLT_fnc_Marker;</code>

sleep value has been increased
